import '../styles/style.scss'
import { Inter } from 'next/font/google'
import localFont from "next/font/local";

const inter = Inter({ subsets: ['latin'] })

export const clashDisplay = localFont({
  src: "../public/fonts/ClashDisplay-Variable.ttf",
});

// import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clashDisplay.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
