import "../styles/style.scss";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

//definiran inter, al nikad ga ne korists
const inter = Inter({ subsets: ["latin"] });

export const clashDisplay = localFont({
  src: "../public/fonts/ClashDisplay-Variable.ttf",
});

// sta je ovo i zasto se koristi
// import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* zasto si iskljuciva hydration error? */}
      <body className={clashDisplay.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
